name: pangeo
channels:
  - conda-forge
dependencies:
  - conda=4.6.3
  - nomkl
  - fsspec=0.2.0
  - s3fs=0.2.0
  - gcsfs=0.2.0
  - intake=0.4.1
  - intake-xarray=0.3.0
  - msgpack-python=0.6.1
  - curl=7.64
  - python=3.6
  - zarr=2.2.0
  - h5py=2.9.0
  - dask=1.1
  - distributed=1.25.3
  - matplotlib=3.0
  - nbserverproxy=0.8.8
  - jupyter=1.0.0
  - ipywidgets=7.4.2
  - graphviz=2.38
  - jupyterlab=0.35.4
  - libgdal=2.4.0
  - netcdf4=1.4.2
  - boto3=1.9.91
  - hvplot=0.4.0
  - geoviews-core=1.6.2
  - ipyleaflet=0.8.1
  - datashader=0.6.9
  - requests=2.21.0
  - pandas=0.24.1
  - geopandas=0.4.0
  - rasterio=1.0.18
  - tornado=5.1.1
  - pip:
    - sat-search==0.2.0
    - dask-labextension==0.3.1
    - kubernetes==8.0.1
    - git+https://github.com/dask/dask-kubernetes.git@ed22c059f649b75bec580183a65aea7b9c9a0233
    - git+https://github.com/scottyhq/xarray.git@fileobj
    - git+https://github.com/scottyhq/h5netcdf.git@fileobj
